---
version: 2.1

defaults: &defaults
  docker:
    - image: 816897914983.dkr.ecr.us-east-1.amazonaws.com/circleci-image

jobs:
  tests:
    <<: *defaults
    steps:
      - checkout: {}
      - run: make deps
      - run: make test ARGS="--junitxml=reports/junit.xml"
      - store_test_results:
          path: reports

workflows:
  version: 2
  main:
    jobs:
      - tests:
          context: sdi-management
