replicas: 1
imagePullSecret: dockerhub-creds
image:
  repository: reactioncommerce/reaction-cron-jobs
  tag: sftp-from-radial-69493f4
schedule: "*/2 * * * *"
config:
  s3BucketName: sdi-prod-feeds-order-status-import-bobs
  sftpEndpoint: sftp.remotetools.gsipartners.com
  sftpHomedir: /home/bobsftp02
  sftpPassword: >-
        AgDEP2VKigQ/z1n1tzcYZb9P9rz7mXfGklld1x+wKtnNzWAYaJ/V8oZp8ZxOP1/gx5bRWHldc61ModooLhlaxFsbAnbr7ai7WIycd3HRv4F3tFwqmypKsRF6vYjscmgtBUZjGuvn0W7xjF2gVfxhxlcctnWZ1t7nXjpoSnP50Hzi3E0RowlZfBgotQpbBcxYUTZdiitovi1bXbXEBFokX2NvzdwbL2LFl/b9U+vuWbuiT+JeGz0raz5KfdI0qEXRAEN1I4m+TG652zwLwJCZk5cp3CyMfan911hVB/Iy9UTXvzUXzyu3roPH9C9BWZifNgnsDjWyFmtMaJIfGwLkm4vEXEqeGhrlplAI1sJ8kCAnqa0awxNxacaVqZUqSj72KSD49QXqu6qAFWR2NmL3QhmqbcyAGrmMubkL9dCCQD3AwffmII8y8Ea3fn+4O5+JBoCDTe12hCiRAeiEgy2rLbmOr/25/0n5GsWJmA49uwt+Sawo/jdl4oyeKfN9f7DaJXuvQbrXb1DZ/LH4DF081zCIhlm7V+0pDkJdR00rlQXrJLawTstRVQ1JpSA1QxOIhm9b02UlHV+1h6Xy0o81EB99yXdmgWenOVCDHdLGRE3x7vEhlVjw9xHNMt+rlw9SB93zigMvZ+Tj0QaQAGTBUB2D4km7XJTdwx6N/AOuqhveCD8dzdbyYcy9CiPYsxMdbOaONMzfiTV0xXzk
  sftpUsername: bobsftp02
  sftpSubfolders:
    adjusted: outbound/order_status/BOBS/adjusted
    backordered: outbound/order_status/BOBS/backordered
    canceled: outbound/order_status/BOBS/canceled
    ispuStatus: outbound/order_status/BOBS/ISPU_status
    opened: outbound/order_status/BOBS/opened
    returned: outbound/order_status/BOBS/returned
    shipped: outbound/order_status/BOBS/shipped
resources:
  requests:
    memory: 1Gi
    cpu: "1"
  limits:
    memory: 2Gi
    cpu: "1"
