{{- $fullName := include "reaction-core.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "reaction-core.name" . }}
    app.kubernetes.io/component: core
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "reaction-core.chart" . }}
data:
  SITE_CODE: {{ required "config.siteCode not defined." .Values.config.siteCode | quote }}
  INITIAL_IMPORT: {{ required "config.initialImport not defined." .Values.config.initialImport | quote }}
  STARTING_NEW_CUSTOMER_NUMBER: {{ required "config.startingNewCustomerNumber not defined." .Values.config.startingNewCustomerNumber | quote }}
  SKIP_FIXTURES: {{ required "config.skipFixtures not defined." .Values.config.skipFixtures | quote }}
  ROOT_URL: {{ required "config.rootUrl not defined." .Values.config.rootUrl | quote }}
  CART_REFERENCE_ID_PREFIX: {{ required "config.cartReferenceIdPrefix not defined." .Values.config.cartReferenceIdPrefix | quote }}
  ETCD_URL: {{ required "config.etcdUrl not defined." .Values.config.etcdUrl | quote }}
  JAEGER_ENDPOINT: {{ required "config.jaegerEndpoint not defined." .Values.config.jaegerEndpoint | quote }}
  DEFAULT_SHIPPING_METHOD_ID: {{ required "config.defaultShippingMethodId not defined." .Values.config.defaultShippingMethodId | quote }}
  DEFAULT_SHIPPING_METHOD_RATE: {{ required "config.defaultShippingMethodRate not defined." .Values.config.defaultShippingMethodRate | quote }}
  REACTION_LOG_FORMAT: {{ required "config.logFormat not defined." .Values.config.logFormat | quote }}
  REACTION_LOG_LEVEL: {{ required "config.logLevel not defined." .Values.config.logLevel | quote }}
  REACTION_USER: {{ required "config.user not defined." .Values.config.user | quote }}
  GRAPHQL_INTROSPECTION_ENABLED: {{ required "config.graphqlIntrospectionEnabled not defined." .Values.config.graphqlIntrospectionEnabled | quote }}
  GRAPHQL_PLAYGROUND_ENABLED: {{ required "config.graphqlPlaygroundEnabled not defined." .Values.config.graphqlPlaygroundEnabled | quote }}
  HYDRA_ADMIN_URL: {{ required "config.hydraAdminUrl not defined." .Values.config.hydraAdminUrl | quote }}
  HYDRA_OAUTH2_INTROSPECT_URL: {{ required "config.hydraOauth2IntrospectUrl not defined." .Values.config.hydraOauth2IntrospectUrl | quote }}
  KAFKA_BOOTSTRAP_SERVERS: {{ required "config.kafkaBootstrapServers not defined." .Values.config.kafkaBootstrapServers | quote }}
  KAFKA_CLUSTER: {{ required "config.kafkaCluster not defined." .Values.config.kafkaCluster | quote }}
  SCHEMA_REGISTRY_URL: {{ required "config.kafkaSchemaRegistryUrl not defined." .Values.config.kafkaSchemaRegistryUrl | quote }}
  KAFKA_PARTITIONS_LOYALTY: {{ required "config.kafkaPartitionsLoyalty not defined." .Values.config.kafkaPartitionsLoyalty | quote }}
  KAFKA_PARTITION_ETL_SHIPPABLE_INVENTORY_STATUS: {{ required "config.kafkaPartitionsEtlShippableInventoryStatus not defined." .Values.config.kafkaPartitionsEtlShippableInventoryStatus | quote }}
  KAFKA_TOPIC_CATALOG_IMPORT_ERRORS: {{ required "config.kafkaTopicCatalogImportErrors not defined." .Values.config.kafkaTopicCatalogImportErrors | quote }}
  KAFKA_TOPIC_CATALOG_SYNC_PRODUCTS: {{ required "config.kafkaTopicCatalogSyncProducts not defined." .Values.config.kafkaTopicCatalogSyncProducts | quote }}
  KAFKA_TOPIC_ETL_SHIPPABLE_INVENTORY_STATUS: {{ required "config.kafkaTopicEtlShippableInventoryStatus not defined." .Values.config.kafkaTopicEtlShippableInventoryStatus | quote }}
  KAFKA_TOPIC_ETL_SHIPPABLE_INVENTORY_STREAM: {{ required "config.kafkaTopicEtlShippableInventoryStream not defined." .Values.config.kafkaTopicEtlShippableInventoryStream | quote }}
  KAFKA_TOPIC_IMPORT_ORDER_STATUS_ORDERS: {{ required "config.kafkaTopicImportOrderStatusOrders not defined." .Values.config.kafkaTopicImportOrderStatusOrders | quote }}
  KAFKA_TOPIC_IMPORT_TAX_CODES_TAXCODES: {{ required "config.kafkaTopicImportTaxCodesTaxcodes not defined." .Values.config.kafkaTopicImportTaxCodesTaxcodes | quote }}
  KAFKA_TOPIC_LOYALTY_PLUGIN_DB_UPDATES: {{ required "config.kafkaTopicLoyaltyPluginDbUpdates not defined." .Values.config.kafkaTopicLoyaltyPluginDbUpdates | quote }}
  KAFKA_TOPIC_LOYALTY_PLUGIN_DB_UPDATES_STATUS: {{ required "config.kafkaTopicLoyaltyPluginDbUpdatesStatus not defined." .Values.config.kafkaTopicLoyaltyPluginDbUpdatesStatus | quote }}
  KAFKA_TOPIC_PRICEBOOKS: {{ required "config.kafkaTopicPricebooks not defined." .Values.config.kafkaTopicPricebooks | quote }}
  KAFKA_TOPIC_PRICES_BY_ID: {{ required "config.kafkaTopicPricesById not defined." .Values.config.kafkaTopicPricesById | quote }}
  KAFKA_TOPIC_PRODUCT_IMPORT_ERRORS: {{ required "config.kafkaTopicProductImportErrors not defined." .Values.config.kafkaTopicProductImportErrors | quote }}
  KAFKA_TOPIC_PRODUCT_IMPORT_ERRORS_PARTITIONS: {{ required "config.kafkaTopicProductImportErrorsPartitions not defined." .Values.config.kafkaTopicProductImportErrorsPartitions | quote }}
  KAFKA_TOPIC_PRODUCT_IMPORT_PRODUCTS: {{ required "config.kafkaTopicProductImportProducts not defined." .Values.config.kafkaTopicProductImportProducts | quote }}
  KAFKA_TOPIC_PRODUCT_IMPORT_PRODUCTS_PARTITIONS: {{ required "config.kafkaTopicProductImportProductsPartitions not defined." .Values.config.kafkaTopicProductImportProductsPartitions | quote }}
  INVENTORY_PLUGIN_BATCH_CONSUME_SIZE: {{ required "config.inventoryPluginBatchConsumeSize is not defined." .Values.config.inventoryPluginBatchConsumeSize | quote }}
  SHIPPABLE_INVENTORY_CONSUMER_ENABLED: {{ required "config.inventoryShippableInventoryConsumerEnabled is not defined." .Values.config.inventoryShippableInventoryConsumerEnabled | quote }}
  LOYALTY_PLUGIN_BATCH_CONSUME_SIZE: {{ required "config.loyaltyPluginBatchConsumeSize is not defined." .Values.config.loyaltyPluginBatchConsumeSize | quote }}
  LOYALTY_CONSUMER_ENABLED: {{ required "config.loyaltyConsumerEnabled is not defined." .Values.config.loyaltyConsumerEnabled  | quote }}
  ORDER_EXPORT_RADIAL_URL: {{ required "config.orderExportRadialUrl is not defined." .Values.config.orderExportRadialUrl | quote }}
  PRICING_CONSUMER_ENABLED: {{ required "config.pricingConsumerEnabled is not defined." .Values.config.pricingConsumerEnabled | quote }}
  PRICING_GRAPHQL_URL: {{ required "config.pricingGraphqlUrl is not defined." .Values.config.pricingGraphqlUrl | quote }}
  PRODUCT_CONSUMER_ENABLED: {{ required "config.productConsumerEnabled is not defined." .Values.config.productConsumerEnabled | quote }}
  PRODUCT_PUBLISHER_AUTO_PUBLISH: {{ required "config.productPublisherAutoPublish is not defined." .Values.config.productPublisherAutoPublish | quote }}
  TAXES_CONSUMER_ENABLED: {{ required "config.taxesConsumerEnabled is not defined." .Values.config.taxesConsumerEnabled  | quote }}
  MASTER_PUBLISH_CONSUMER_ENABLED: {{ required "config.masterPublishConsumerEnabled is not defined." .Values.config.masterPublishConsumerEnabled | quote }}
  METRICS_ENABLED: {{ required "config.metricsEnabled is not defined." .Values.config.metricsEnabled  | quote }}
  METRICS_HOST: {{ required "config.metricsHost is not defined." .Values.config.metricsHost  | quote }}
  METRICS_PATH: {{ required "config.metricsPath is not defined." .Values.config.metricsPath  | quote }}
  METRICS_PORT: {{ required "config.metricsPort is not defined." .Values.config.metricsPort  | quote }}
