apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: core
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "reaction-core.chart" . }}
data:
  SITE_CODE: {{ required "core.siteCode not defined." .Values.core.siteCode | quote }}
  SERVER_TYPE: {{ required "core.serverType not defined." .Values.core.serverType | quote }}
  STARTING_NEW_CUSTOMER_NUMBER: {{ required "core.startingNewCustomerNumber not defined." .Values.core.startingNewCustomerNumber | quote }}
  SKIP_FIXTURES: {{ required "core.skipFixtures not defined." .Values.core.skipFixtures | quote }}
  ROOT_URL: {{ required "core.rootUrl not defined." .Values.core.rootUrl | quote }}
  CART_REFERENCE_ID_PREFIX: {{ required "core.cartReferenceIdPrefix not defined." .Values.core.cartReferenceIdPrefix | quote }}
  ETCD_URL: {{ required "core.etcdUrl not defined." .Values.core.etcdUrl | quote }}
  JAEGER_ENDPOINT: {{ required "core.jaegerEndpoint not defined." .Values.core.jaegerEndpoint | quote }}
  DEFAULT_SHIPPING_METHOD_ID: {{ required "core.defaultShippingMethodId not defined." .Values.core.defaultShippingMethodId | quote }}
  DEFAULT_SHIPPING_METHOD_RATE: {{ required "core.defaultShippingMethodRate not defined." .Values.core.defaultShippingMethodRate | quote }}
  REACTION_LOG_FORMAT: {{ required "core.logFormat not defined." .Values.core.logFormat | quote }}
  REACTION_LOG_LEVEL: {{ required "core.logLevel not defined." .Values.core.logLevel | quote }}
  REACTION_USER: {{ required "core.user not defined." .Values.core.user | quote }}
  GRAPHQL_INTROSPECTION_ENABLED: {{ required "core.graphqlIntrospection not defined." .Values.core.graphqlIntrospection | quote }}
  GRAPHQL_PLAYGROUND_ENABLED: {{ required "core.graphqlPlayground not defined." .Values.core.graphqlPlayground | quote }}
