apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-hydra
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: core
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "reaction-core.chart" . }}
data:
  HYDRA_ADMIN_URL: {{ required "hydra.adminUrl not defined." .Values.hydra.adminUr | quote }}
  HYDRA_OAUTH2_INTROSPECT_URL: {{ required "hydra.oauth2IntrospectUrl not defined." .Values.hydra.oauth2IntrospectUrl | quote }}
