apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-orderexport
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: core
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "reaction-core.chart" . }}
data:
  ORDER_EXPORT_RADIAL_URL: {{ required "orderExport.radialUrl is not defined." .Values.orderExport.radialUrl | quote }}
