{{- $fullName := include "reaction-core.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-product
  labels:
    app.kubernetes.io/name: {{ include "reaction-core.name" . }}
    app.kubernetes.io/component: core
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "reaction-core.chart" . }}
data:
  PRODUCT_CONSUMER_ENABLED: {{ required "product.consumerEnabled is not defined." .Values.product.consumerEnabled | quote }}
  PRODUCT_PUBLISHER_AUTO_PUBLISH: {{ required "product.publisherAutoPublish is not defined." .Values.product.publisherAutoPublish | quote }}
