apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-productpublisher
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: core
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "reaction-core.chart" . }}
data:
  PRODUCT_PUBLISHER_AUTO_PUBLISH: {{ required "productPublisher.autoPublish is not defined." .Values.productPublisher.autoPublish | quote }}
